import "./globals.css";
// import Header from "./components/Header";
import Footer from "./components/Footer";
import Hero from "./components/Hero";

export const metadata = {
  title: "Muhammad Fuzail Portfolio",
  description: "Generated by create next app",
}
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Hero />
        {children}
        <Footer />
      </body>
    </html>
  );
}
